### ISSUE TITLE
Fails to compile on Unity 5.3

### ISSUE THREAD

**Issue by alexjhetherington** [LogicalError/realtime-CSG-for-unity#352]
Assets/RealtimeCSG/Plugins/API/Foundation/Runtime/GeneratedMeshContents.cs(77,30): error CS1501: No overload for method `SetTriangles' takes `3' arguments

`mesh.SetTriangles(indices, 0, calculateBounds: true);`

https://docs.unity3d.com/530/Documentation/ScriptReference/Mesh.SetTriangles.html

**Comment by Kerfuffles** [comment]
Hey, thanks for this. The oldest supported version of RCSG is 5.4, so this is to be expected.
