### ISSUE TITLE
Fails to compile on 5.4

### ISSUE THREAD

**Issue by alexjhetherington** [LogicalError/realtime-CSG-for-unity#353]
Assets/RealtimeCSG/Plugins/Editor/Scripts/Control/Helpers/MaterialUtility.cs(205,58): error CS0117: `UnityEngine.Rendering.GraphicsSettings' does not contain a definition for `renderPipelineAsset'

Assets/RealtimeCSG/Plugins/Editor/Scripts/Control/Helpers/MaterialUtility.cs(288,41): error CS0266: Cannot implicitly convert type `object' to `bool'. An explicit conversion exists (are you missing a cast?)

**Comment by Kerfuffles** [comment]
I am currently waiting on feedback, on if it is okay to bump the minimum version to 20xx releases. I don't think that many, if anyone is using anything older, as the older versions are out of support.

**Comment by Kerfuffles** [comment]
I am currently working on making the latest 2019 LTS the minimum version going forward. Older releases will not be removed, however!
